name: CI for Tenx Insurance Project

on:
  push:
    branches: [ main, task-1, task-2, task-3, task-4 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 scripts/ --max-line-length=100 --ignore=E203,W503

    - name: Run Task 1 Notebook (Optional)
      run: |
        pip install nbconvert
        jupyter nbconvert --to notebook --execute notebooks/task-1-eda.ipynb --output executed-task-1.ipynb

    - name: Upload EDA Output (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: eda-notebook
        path: executed-task-1.ipynb
